name: Deploy to development env

on:
  push:
    branches:
    - dev
    paths:
    - src/**
    - public/**
    - package*.json
    - .github/workflows/deploy_development.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Install SSH Key
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-host: ${{ secrets.SSH_HOST_NEW_IP }}
        ssh-port: ${{ secrets.SSH_HOST_NEW_PORT }}
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Node JS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run TypeScript typecheck
      run: npm run typecheck
    - name: Set git commit
      run: echo "VITE_GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build app
      env:
        VITE_ENV: development
        VITE_OSM_API_URL: ${{ secrets.REACT_APP_OSM_API_URL }}
        VITE_OSM_OAUTH2_CLIENT_ID: ${{ secrets.REACT_APP_OSM_OAUTH2_CLIENT_ID }}
        VITE_OSM_OAUTH2_CLIENT_SECRET: ${{ secrets.REACT_APP_OSM_OAUTH2_CLIENT_SECRET }}
        VITE_BACKEND_API_URL: ${{ secrets.REACT_APP_BACKEND_API_URL_NEW }}
      run: npm run build
    - name: Create robots.txt
      run: |
        cat << 'EOF' >> build/robots.txt
        # https://www.robotstxt.org/robotstxt.html
        User-agent: *
        Disallow: /
        EOF
    - name: Run deploy script on host
      run: |
        scp -rp -P${{ secrets.SSH_HOST_NEW_PORT }} build/* ${{ secrets.SSH_USER_NEW }}@${{ secrets.SSH_HOST_NEW_IP }}:~/dev-static/